<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/3/10
 * Time: 19:32
 */

namespace BlankPhp;


use BlankPhp\Cache\CacheManager;
use BlankPhp\Config\Config;
use BlankPhp\Config\LoadConfig;
use BlankPhp\Connect\Connect;
use BlankPhp\Contract\CookieContract;
use BlankPhp\Cookie\Cookie;
use BlankPhp\Database\Database;
use BlankPhp\Database\Grammar\Grammar;
use BlankPhp\Database\Grammar\MysqlGrammar;
use BlankPhp\Exception\Error;
use BlankPhp\Exception\NotFoundClassException;
use BlankPhp\Factory\FactoryBase;
use BlankPhp\Kernel\ConsoleKernel;
use BlankPhp\Kernel\HttpKernel;
use BlankPhp\Log\Log;
use BlankPhp\Provider\RegisterProvider;
use BlankPhp\Request\Request;
use BlankPhp\Response\Response;
use BlankPhp\Route\Route;
use BlankPhp\Route\Router;
use BlankPhp\Scheme\Scheme;
use BlankPhp\Session\Session;
use BlankPhp\View\StaticView;
use BlankPhp\View\View;

class Application extends Container
{

    private $version = '0.1.3-dev';

    private $boot = false;

    private $connect = [];

    protected $bootstraps = [
        LoadConfig::class => 'load',
        Error::class => 'register',
        RegisterProvider::class => 'register',
    ];

    public static function init()
    {
        return self::getInstance();
    }

    protected function __construct()
    {
        $this->registerService();
        $this->registerBase();
        $this->registerDirName();
        $this->bootstrap();
    }

    public function bootstrap(): void
    {
        if ($this->boot) {
            return;
        }
        foreach ($this->bootstraps as $provider => $method) {
            $this->call($provider, $method, null, [$this]);
        }
        $this->boot = true;
    }

    public function registerDirName(): void
    {
        define('PUBLIC_PATH', APP_PATH . DIRECTORY_SEPARATOR . 'public/');
    }

    public function registerService(): void
    {
        $temp = [
            'kernel' => [\BlankPhp\Contract\Kernel::class, HttpKernel::class],
            'console' => ConsoleKernel::class,
            'request' => [\BlankPhp\Contract\Request::class, Request::class],
            'route' => [\BlankPhp\Contract\Route::class, Route::class],
            'router' => [Router::class],
            'app' => [\BlankPhp\Contract\Container::class, __CLASS__],
            'db' => Database::class,
            'db.grammar' => [Grammar::class, MysqlGrammar::class],
            'view' => [\BlankPhp\Contract\View::class, View::class],
            'view.static' => StaticView::class,
            'cookie' => [CookieContract::class, Cookie::class],
            'config' => Config::class,
            'session' => [\BlankPhp\Contract\Session::class, Session::class],
            'scheme' => Scheme::class,
            'response' => Response::class,
            'cache' => [CacheManager::class],
            'cache.drive' => [CacheManager::class],
            'redis' => [Redis::class],
            'log' => Log::class
        ];
        array_walk($temp, array($this, 'bind'));
        unset($temp);
    }

    /**
     * @param string $abstract
     * @param array $parameters
     * @return mixed|void|null
     */
    public function make(string $abstract, $parameters = [])
    {
        //需要比较一下hash
        if (!$this->has($abstract)) {
            if (!empty($parameters) && class_exists($abstract)) {
                return $this->instance($abstract, new $abstract(...$parameters));
            }
        }
        return parent::make($abstract, $parameters);
    }

    public function pushConnect($conn): void
    {
        $this->connects[] = $conn;
    }

    protected function disconnects(): void
    {
        foreach ($this->connects as $item) {
            /** @var Connect $item */
            $item->disconnect();
        }
    }

    /**
     * @return void
     */
    public function registerBase(): void
    {
        $this->instance('app', $this);
        static::$instance = $this;
    }

    /**
     * @param $abstract
     * @param string $name
     * @return array|mixed
     */
    public function getSignal($abstract, $name = '')
    {
        if (empty($name)) {
            return $this->signal[$abstract] ?? [];
        }

        return $this->signal[$abstract][$name] ?? [];
    }

    /**
     * @param $abstract
     */
    public function unsetSignal($abstract): void
    {
        unset($this->signal[$abstract]);
    }

    public function flush(): void
    {
        parent::flush(); // TODO: Change the autogenerated stub
        $this->disconnects();
    }


}


