<?php


namespace BlankPhp\Proxy;


use BlankPhp\Provider\Provider;

//动态代理应该原生支持
class ProxyServiceProvider extends Provider
{

    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }

}