<?php

/*
 * This file is part of the /blankphp/framework.
 *
 * (c) 沉迷 <1136589038@qq.com>
 *
 * This source file is subject to the MIT license that is bundled.
 */

namespace BlankPhp\Proxy;

use BlankPhp\Provider\Provider;

//动态代理应该原生支持
class ProxyServiceProvider extends Provider
{
    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }
}
