name: Lint Code

on: [push,pull_request]


jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [ '7.2', '7.3', '7.4','8.0','8.1' ]
        steps:
            - uses: actions/checkout@v2
            - name: Setup PHP Action
              uses: shivammathur/setup-php@2.16.0
              with:
                    php-version: ${{ matrix.php }}
            - name: Validate composer.json and composer.lock
              run: composer validate --strict
            - name: Cache Composer packages
              id: composer-cache
              uses: actions/cache@v2
              with:
                  path: vendor
                  key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-php-
            - name: Install dependencies
              run: composer install --prefer-dist --no-progress
            - name: Check style
              run: vendor/bin/php-cs-fixer fix src --using-cache=no --diff --config=.php-cs-fixer.php --dry-run --ansi
            - name: Run stan
              run: composer stan
